import type { Dictionary } from "@puckeditor/core";

// Textos da interface do Puck em português.
export const dicionario: Dictionary = {
  "header-publish": "Publicar",
  "header-undo": "desfazer",
  "header-redo": "refazer",
  "header-toggle-leftsidebar": "Mostrar/ocultar painel esquerdo",
  "header-toggle-rightsidebar": "Mostrar/ocultar painel direito",
  "header-toggle-menubar": "Mostrar/ocultar menu",
  "action-selectparent": "Selecionar bloco pai",
  "action-duplicate": "Duplicar",
  "action-delete": "Excluir",
  "label-page": "Página",
  "label-component": "Bloco",
  "outline-empty": "Nenhum bloco",
  "outline-item-collapse": "Recolher",
  "outline-item-expand": "Expandir",
  "outline-header-title": "Estrutura",
  "outline-header-collapseall": "Recolher tudo",
  "outline-item-duplicate": "Duplicar",
  "outline-item-delete": "Excluir",
  "drawer-category-collapse": "Recolher {title}",
  "drawer-category-expand": "Expandir {title}",
  "drawer-category-other": "Outros",
  "canvas-noconfig": "Sem configuração para {type}",
  "field-readonly": "Somente leitura",
  "field-arrayitem-summary": "Item {index}",
  "field-arrayitem-duplicate": "Duplicar",
  "field-arrayitem-delete": "Excluir",
  "viewport-zoom-in": "Aproximar",
  "viewport-zoom-out": "Afastar",
  "viewport-zoom-auto": "{zoom}% (automático)",
  "viewport-toggle-menu": "Menu de telas",
  "viewport-switch": "Ver em {label}",
  "viewport-switch-default": "Trocar tela",
  "plugin-blocks": "Blocos",
  "plugin-outline": "Estrutura",
  "plugin-fields": "Propriedades",
  "plugin-components": "Blocos",
  "layout-maximize": "maximizar",
  "layout-minimize": "minimizar",
  "loader-loading": "carregando",
};
